spring.application.name=learnspringsecurity

logging.level.org.springframework.security=DEBUG

spring.security.user.name=dummyuser
spring.security.user.password=dummypassword

server.servlet.session.cookie.same-site=strict