# all common props
spring.application.name=learnspringboot

# to set active profile in application.properties 
# we can also manage through env variabbles 
# if we pass through container

spring.profiles.active=dev

# currency configuration
currency-config.url=http://default.rohitkuna.com
currency-config.username=defaultuser
currency-config.key=defaultkey

# actuator endpoints - to expose all actuator endpoints
# management.endpoints.web.exposure.include=*

# to expose only a few actuator endpoints, as * will give more info, more memory consumption, more cpu consumption, 
# so we can specify only the required endpoints
management.endpoint.web.exposure.include=health,metrics
